export type StudioOnboardingResponse = {
  id: string;
  projectSlug: string;
  projectName: string;
  clientName: string;
  status: 'draft' | 'submitted';
  contactName: string;
  contactEmail: string;
  contactPhone: string;
  approvalRole: string;
  audienceType: string;
  projectGoals: string;
  primaryAudience: string;
  services: string[];
  accessNeeds: string;
  brandAssetsStatus: string;
  technicalAccounts: string;
  preferredDeadline: string;
  launchConstraints: string;
  contentNotes: string;
  consentToTerms: boolean;
  currentWebsite: string;
  budgetRange: string;
  competitors: string;
  decisionProcess: string;
  specificFeatures: string;
  socialPresence: string;
  toneStylePreferences: string;
  previousAgencyExperience: string;
  existingIntegrations: string[];
  missingContentOwner: string;
  missingContentDueDate: string;
  missingAccessOwner: string;
  missingAccessDueDate: string;
  updateCadence: string;
  preferredUpdateChannel: string;
  urgentChannel: string;
  meetingAvailability: string;
  scopeInclusions: string;
  scopeExclusions: string;
  revisionRounds: string;
  changeRequestAuthority: string;
  scopeBoundaryAccepted: boolean;
  submittedAt: string;
  lastSavedAt: string;
  source: 'supabase' | 'demo';
};
